// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9-jZx7uOrne6lNaAgfMVH5Nm3v2x-GI8',
    appId: '1:3991273433:web:e842a2dd32b1aa9147e3c8',
    messagingSenderId: '3991273433',
    projectId: 'medicine-app-fca0c',
    authDomain: 'medicine-app-fca0c.firebaseapp.com',
    storageBucket: 'medicine-app-fca0c.firebasestorage.app',
    measurementId: 'G-QKZ5CJDJKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV2Z8PLfHQ0SEgtg26rA_3629h2Cm-TX8',
    appId: '1:3991273433:android:02c1a10e9154ccb147e3c8',
    messagingSenderId: '3991273433',
    projectId: 'medicine-app-fca0c',
    storageBucket: 'medicine-app-fca0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyQzlruT1I59BUd1k5Mk-72J9TuAo-ck0',
    appId: '1:3991273433:ios:547efc8a6ad5bc3c47e3c8',
    messagingSenderId: '3991273433',
    projectId: 'medicine-app-fca0c',
    storageBucket: 'medicine-app-fca0c.firebasestorage.app',
    iosBundleId: 'com.medicine.medicineDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyQzlruT1I59BUd1k5Mk-72J9TuAo-ck0',
    appId: '1:3991273433:ios:547efc8a6ad5bc3c47e3c8',
    messagingSenderId: '3991273433',
    projectId: 'medicine-app-fca0c',
    storageBucket: 'medicine-app-fca0c.firebasestorage.app',
    iosBundleId: 'com.medicine.medicineDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9-jZx7uOrne6lNaAgfMVH5Nm3v2x-GI8',
    appId: '1:3991273433:web:08b9c2ddb9c153d247e3c8',
    messagingSenderId: '3991273433',
    projectId: 'medicine-app-fca0c',
    authDomain: 'medicine-app-fca0c.firebaseapp.com',
    storageBucket: 'medicine-app-fca0c.firebasestorage.app',
    measurementId: 'G-N4TDLHKEK9',
  );
}
