// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6WOu-B-wOEE-xUVGaoZ1dmH-R8S3J-A8',
    appId: '1:521359123666:web:36d05569be4c7b57dc790b',
    messagingSenderId: '521359123666',
    projectId: 'medicine-delivery-b47b4',
    authDomain: 'medicine-delivery-b47b4.firebaseapp.com',
    storageBucket: 'medicine-delivery-b47b4.firebasestorage.app',
    measurementId: 'G-LYKGMJGNPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHTv4ACeg62kRQlVv-hSG1sLVNJKJrp3w',
    appId: '1:521359123666:android:1ddae144e4518231dc790b',
    messagingSenderId: '521359123666',
    projectId: 'medicine-delivery-b47b4',
    storageBucket: 'medicine-delivery-b47b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtwWrk-rBpNqeLt_gkfeSsyVcaXJUoO8U',
    appId: '1:521359123666:ios:106816187d2ece52dc790b',
    messagingSenderId: '521359123666',
    projectId: 'medicine-delivery-b47b4',
    storageBucket: 'medicine-delivery-b47b4.firebasestorage.app',
    iosBundleId: 'com.medicine.medicineDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtwWrk-rBpNqeLt_gkfeSsyVcaXJUoO8U',
    appId: '1:521359123666:ios:106816187d2ece52dc790b',
    messagingSenderId: '521359123666',
    projectId: 'medicine-delivery-b47b4',
    storageBucket: 'medicine-delivery-b47b4.firebasestorage.app',
    iosBundleId: 'com.medicine.medicineDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6WOu-B-wOEE-xUVGaoZ1dmH-R8S3J-A8',
    appId: '1:521359123666:web:20f24c65c8a0bfdadc790b',
    messagingSenderId: '521359123666',
    projectId: 'medicine-delivery-b47b4',
    authDomain: 'medicine-delivery-b47b4.firebaseapp.com',
    storageBucket: 'medicine-delivery-b47b4.firebasestorage.app',
    measurementId: 'G-GGBLXR3T0H',
  );
}
